### ISSUE TITLE
Capability to pass filters into the JSON thus into the request headers, body and query parameters

### ISSUE THREAD

**Issue by aderici** [AhaMove/metabase-http-driver#1]
Thank you for your contribution to metabase community with this great driver. I was able to make it work with the recent versions of metabase! This really came at a time where i desperately needed it.

I noticed this somehow lacks the ability to provide filter parameters, thus very limited in the use case. Do you think this functionality can be added? I am using raw sql query editor and i'd like to add a filter with using {{filtername}} syntax. 

I think at least two things prevent it. First the query is processed with every change and metabase pops up filters panel if you added {{}} in the sql drivers but this new driver doesn't do it. And also the json validator gives errors when it sees {{}}.

I would love to help in any way i can but i'm stuck here as im not proficient in java nor clojure.

Thanks a lot again for this great driver, best regards,

**Comment by romvarac** [comment]
A missing field filter in driver, thanks for for your remind. Added code and you could be verify this :D

**Comment by aderici** [comment]
Thank you so much! I really needed this,

One thing i noticed is,  following sample works :

```
{
  "url": "https://sample.test.web.url",
  "method": "POST",
  "headers": {
    "Authorization": {{myTokenFromParameter}}
  },
  "body": {
    "foo": "bar"
  },
  "result": {
    "path": "rows"
  }
}
```

But unfortunately i could now find a way to use parameters in terms of string concatenation. As an example this does not work : 


```
{
  "url": "https://sample.test.web.url?myparameter=" + {{myVariableFromParameter}},
  "method": "POST",
  "headers": {
    "Authorization": {{myTokenFromParameter}}
  },
  "body": {
    "foo": "bar"
  },
  "result": {
    "path": "rows"
  }
}
```

Do you know a successful way of using filters to provide query string parameters or changing a part of the url ?

Best regards,

**Comment by romvarac** [comment]
How to you set plugin. My test
<img width="1433" alt="Screen Shot 2020-12-11 at 16 36 02" src="https://user-images.githubusercontent.com/20069996/101887147-0ac6c580-3bcf-11eb-94e5-d52a9e915545.png">

**Comment by aderici** [comment]
Hi, thanks for your quick response!

Please try to set test2345 for both parameters and run the query, it gives an error for json validation

Unexpected character ('+' (code 43)): was expecting comma to separate Object entries at [Source: (StringReader); line: 2, column: 54]

Seems you cant simply concatenate 2 strings with a + parser wont allow that.

You cant also put your variable inside the original string like "Test {{myvar}} test" because if your variable is of type text metabase add doublequotes at the begining and end so it will break the string,

**Comment by romvarac** [comment]
I'v just updated field filter.
My test
```
{
  "url": "https://blockchain.info/blocks?format={{format}}",
  "result": {
    "path": "blocks",
    "fields": ["height", "time"]
  }
}
```
Thanks for your suggestion :D. 👍

**Comment by aderici** [comment]
Hello, i was able to make it work as expected. This is great to have this capability on metabase. Thanks a lot for your efforts and contribution, i think we should promote this on the metabase community

**Comment by makwasi1** [comment]
Hello @romvarac & @aderici 
I have a question so when i provided the table definitions i managed to create a table in my database, what am still not sure of is if its possible to add data to the the table that has been created. Thanks

Kind regards
