### ISSUE TITLE
Adding the REST url directly intsead of running it as a native querry

### ISSUE THREAD

**Issue by makwasi1** [AhaMove/metabase-http-driver#2]
I was asking if its possible to add a URL from the starting page like other databases instead of running it as a native query

**Comment by aderici** [comment]
I guess you are trying to achieve usage of regular questions (non native). In that case system knows how to speak sql. But it wouldnt know how to speak to your api’s language and specific parameters etc. So i think it will not allow you to use filtering and other features of the visual query builder unless its one single system that we know how to speak to, and not a generic url,

**Comment by makwasi1** [comment]
Yes i guess want i want to achieve is being able to store my api response into a database like format so that i can ask more (non native ) questions. And also i would love to understand this code more am new to clojure any brief insight can be of help in understanding how the code runs.

**Comment by makwasi1** [comment]
@aderici Hello is it possible to store the API's response in a table like structure for me to run questions on it.

**Comment by aderici** [comment]
Hi,

Do you have a database that you can use? If so i suggest using a tool like node-red to pull data from the api and feed it into your database if you dont need the data to be real-time. Would that be a feasible solution for you?

**Comment by makwasi1** [comment]
Thanks @aderici  for the response. I need my data to be in real time since its coming from forms that are constantly changing.Maybe i would like to know how you are using this driver specifically? i might be asking so much from it since its still in development.

**Comment by aderici** [comment]
For a specific api endpoint like https://myapi.com/who-is-online?location={{filter-location}} we create a native question and feed filter parameters to it and visualize the data in tables or charts. In our case end user doesnt slice and dice but they see pre-designed reports/charts/dashboards so native query does the job for me.

**Comment by makwasi1** [comment]
OK that's a good starting point for me, thanks again for the feedback and help. kind regards.
