### ISSUE TITLE
Build Error when creating jar file

### ISSUE THREAD

**Issue by makwasi1** [AhaMove/metabase-http-driver#3]
Hello i have made some changes to the code on my side and i would want to test them out but i cant generate a jar file.
I keep getting this error. 

> `C:\Users\crism\OneDrive\Desktop\Driver\metabase-http-driver-1\src\metabase>lein uberjar
> Compiling metabase.driver.http
> Syntax error macroexpanding at (parameters.clj:1:1).
> Execution error (FileNotFoundException) at metabase.driver.http.parameters/loading (parameters.clj:1).
> Could not locate metabase/driver/common/parameters__init.class, metabase/driver/common/parameters.clj or metabase/driver/common/parameters.cljc on classpath.
> 
> Full report at:
> C:\Users\crism\AppData\Local\Temp\clojure-18073727761819680570.edn
> Compilation failed: Subprocess failed (exit code: 1)`

**Comment by romvarac** [comment]
How I can reproduce error?

**Comment by makwasi1** [comment]
Try building from this. i made a small change 
https://github.com/makwasi1/metabase-http-driver-1

**Comment by makwasi1** [comment]
I have solved the issue. i was missing some dependecies. 
Thanks for the feedback..
