### ISSUE TITLE
Adding Fields after defining tables in a database 

### ISSUE THREAD

**Issue by makwasi1** [AhaMove/metabase-http-driver#4]
Hello @romvarac & @aderici 
I have a question so when i provided the table definitions i managed to create a table in my database, what am still not sure of is if its possible to add data to the the table that has been created. Thanks

I managed to create tables using this test case thats in the Readme file
`{
  "tables": [
    {
      "name": "Blocks",
      "url": "https://blockchain.info/blocks?format=json",
      "fields": [
        { "name": "height", "type": "number" },
        { "name": "hash", "type": "string" },
        { "name": "time", "type": "number" },
        { "type": "boolean", "name": "main_chain" }
      ],
      "result": {
        "path": "blocks"
      }
    }
  ]
}`

It created a table called blocks but its empty so i wanted to know if its possible to add data into that table 

Kind regards

_Originally posted by @makwasi1 in https://github.com/AhaMove/metabase-http-driver/issues/1#issuecomment-753366844_

**Comment by makwasi1** [comment]
![Screenshot 2021-01-04 143138](https://user-images.githubusercontent.com/39483317/103531395-49803080-4e9a-11eb-815e-c741630f7d88.png)
it creates a table called blocks. I wanted to find out if its possible to add fields into that table. @thucnc please help out on this one. Thanks

**Comment by aagz** [comment]
@makwasi1 hi, did you solve this issue? I have the same problem. Could you tell me about this?

**Comment by makwasi1** [comment]
Hello @aagz

> @makwasi1 hi, you solved this issue? I have the same problem. Could you tell me about this?

No, I wasn't able to solve this. The table can be created fine but it doesn't seem to read the predefined columns.
Am open to a discussion we can explore this more..

**Comment by aagz** [comment]
@makwasi1 could you reopen your issue?
Metabase 0.36 requires `database_position` field from driver.

I don't use clojure, but will try to add that.

https://github.com/dacort/metabase-athena-driver/issues/50

and 
![image](https://user-images.githubusercontent.com/46520039/117942874-34b61c80-b314-11eb-91f4-97b456995532.png)

**Comment by aagz** [comment]
@makwasi1 hi, I added the database_position parameter, but metabase has a bug, if result block has more than 8 columns, then you should to add 'fields' parameter to 'result' block.

Like this
```JSON
{
  "url" : "https://blockchain.info/blocks?format=json",
  "result" : {
    "path" : "blocks",
    "fields": ["height", "time"]
  }
}
```

Link to fixed repo: https://github.com/aagz/metabase-http-driver

**Comment by makwasi1** [comment]
Thanks, @aagz I shall test it out and see how it works.

**Comment by ricpersi** [comment]
Hi @aagz thanks for your contribution. Is your metabase-http-driver fork now working with the latest metabase 0.39.x versions? Do you mind making a release with the bin plugin? Thanks in advance for your help
